# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hederfuter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 870)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMaximumSize(QtCore.QSize(16777215, 241))
        self.header.setStyleSheet("background-color:white;")
        self.header.setTitle("")
        self.header.setObjectName("header")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headerVLayout = QtWidgets.QVBoxLayout()
        self.headerVLayout.setSpacing(0)
        self.headerVLayout.setObjectName("headerVLayout")
        self.heder1 = QtWidgets.QGroupBox(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heder1.sizePolicy().hasHeightForWidth())
        self.heder1.setSizePolicy(sizePolicy)
        self.heder1.setStyleSheet("*{\n"
"    background-color:white;\n"
"    border-bottom: 2px solid black;\n"
"}\n"
"\n"
"#BinusLabel{\n"
"border:none;\n"
"}\n"
"\n"
"#InternLabel{\n"
"border:none;\n"
"}\n"
"\n"
"#MoreLabel{\n"
"border:none;\n"
"}\n"
"\n"
"#Profilepng{\n"
"border:none;\n"
"}")
        self.heder1.setTitle("")
        self.heder1.setObjectName("heder1")
        self.layoutWidget = QtWidgets.QWidget(self.heder1)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 573, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.heder1HLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.heder1HLayout.setContentsMargins(0, 0, 0, 0)
        self.heder1HLayout.setObjectName("heder1HLayout")
        self.MoreLabel = QtWidgets.QLabel(self.layoutWidget)
        self.MoreLabel.setMaximumSize(QtCore.QSize(50, 50))
        self.MoreLabel.setText("")
        self.MoreLabel.setPixmap(QtGui.QPixmap(":/logo/aa.jpg"))
        self.MoreLabel.setScaledContents(True)
        self.MoreLabel.setObjectName("MoreLabel")
        self.heder1HLayout.addWidget(self.MoreLabel)
        self.BinusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.BinusLabel.setMaximumSize(QtCore.QSize(180, 39))
        self.BinusLabel.setBaseSize(QtCore.QSize(1, 0))
        self.BinusLabel.setText("")
        self.BinusLabel.setPixmap(QtGui.QPixmap(":/logo/binuslogo.jpg"))
        self.BinusLabel.setScaledContents(True)
        self.BinusLabel.setObjectName("BinusLabel")
        self.heder1HLayout.addWidget(self.BinusLabel)
        self.InternLabel = QtWidgets.QLabel(self.layoutWidget)
        self.InternLabel.setMaximumSize(QtCore.QSize(300, 30))
        self.InternLabel.setText("")
        self.InternLabel.setPixmap(QtGui.QPixmap(":/logo/intern.jpg"))
        self.InternLabel.setScaledContents(True)
        self.InternLabel.setObjectName("InternLabel")
        self.heder1HLayout.addWidget(self.InternLabel)
        self.ProfButton = QtWidgets.QPushButton(self.heder1)
        self.ProfButton.setGeometry(QtCore.QRect(1020, 0, 51, 51))
        self.ProfButton.setStyleSheet("border:none;")
        self.ProfButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/1A.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProfButton.setIcon(icon)
        self.ProfButton.setIconSize(QtCore.QSize(45, 45))
        self.ProfButton.setObjectName("ProfButton")
        self.headerVLayout.addWidget(self.heder1)
        self.heder2 = QtWidgets.QGroupBox(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heder2.sizePolicy().hasHeightForWidth())
        self.heder2.setSizePolicy(sizePolicy)
        self.heder2.setMinimumSize(QtCore.QSize(0, 125))
        self.heder2.setStyleSheet("*{\n"
"    border-top: 0.5px solid black;\n"
"    border-bottom: 0.5px solid black;\n"
"}")
        self.heder2.setTitle("")
        self.heder2.setObjectName("heder2")
        self.BinusLogo = QtWidgets.QLabel(self.heder2)
        self.BinusLogo.setGeometry(QtCore.QRect(40, 0, 181, 125))
        self.BinusLogo.setText("")
        self.BinusLogo.setPixmap(QtGui.QPixmap(":/logo/login2.jpg"))
        self.BinusLogo.setScaledContents(True)
        self.BinusLogo.setObjectName("BinusLogo")
        self.headerVLayout.addWidget(self.heder2)
        self.heder3 = QtWidgets.QGroupBox(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heder3.sizePolicy().hasHeightForWidth())
        self.heder3.setSizePolicy(sizePolicy)
        self.heder3.setMaximumSize(QtCore.QSize(16777215, 56))
        self.heder3.setStyleSheet("*{\n"
"    border-top: 0.5px solid black;\n"
"    border-bottom: 0.5px solid black;\n"
"}")
        self.heder3.setTitle("")
        self.heder3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.heder3.setObjectName("heder3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.heder3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BLenk = QtWidgets.QGroupBox(self.heder3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BLenk.sizePolicy().hasHeightForWidth())
        self.BLenk.setSizePolicy(sizePolicy)
        self.BLenk.setStyleSheet("border:none;")
        self.BLenk.setObjectName("BLenk")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BLenk)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.heder3HLayout = QtWidgets.QGroupBox(self.BLenk)
        self.heder3HLayout.setStyleSheet("border:none;\n"
"border-color: white;")
        self.heder3HLayout.setTitle("")
        self.heder3HLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.heder3HLayout.setObjectName("heder3HLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.heder3HLayout)
        self.horizontalLayout_3.setContentsMargins(100, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.HomeButton = QtWidgets.QPushButton(self.heder3HLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeButton.sizePolicy().hasHeightForWidth())
        self.HomeButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HomeButton.setFont(font)
        self.HomeButton.setStyleSheet("border: none;\n"
"padding-bottom:10px;")
        self.HomeButton.setObjectName("HomeButton")
        self.horizontalLayout_3.addWidget(self.HomeButton)
        self.SearchButton = QtWidgets.QPushButton(self.heder3HLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchButton.sizePolicy().hasHeightForWidth())
        self.SearchButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.SearchButton.setFont(font)
        self.SearchButton.setStyleSheet("border: none;\n"
"border-bottom: 3px solid black;\n"
"padding-bottom:10px;")
        self.SearchButton.setObjectName("SearchButton")
        self.horizontalLayout_3.addWidget(self.SearchButton)
        self.horizontalLayout.addWidget(self.heder3HLayout)
        self.Blank = QtWidgets.QGroupBox(self.BLenk)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Blank.sizePolicy().hasHeightForWidth())
        self.Blank.setSizePolicy(sizePolicy)
        self.Blank.setStyleSheet("border:none;")
        self.Blank.setTitle("")
        self.Blank.setObjectName("Blank")
        self.horizontalLayout.addWidget(self.Blank)
        self.SignOutButton = QtWidgets.QPushButton(self.BLenk)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SignOutButton.setFont(font)
        self.SignOutButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SignOutButton.setStyleSheet("border:none;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SignOutButton.setIcon(icon1)
        self.SignOutButton.setIconSize(QtCore.QSize(30, 30))
        self.SignOutButton.setCheckable(False)
        self.SignOutButton.setChecked(False)
        self.SignOutButton.setObjectName("SignOutButton")
        self.horizontalLayout.addWidget(self.SignOutButton)
        self.horizontalLayout_2.addWidget(self.BLenk)
        self.headerVLayout.addWidget(self.heder3)
        self.verticalLayout_3.addLayout(self.headerVLayout)
        self.verticalLayout.addWidget(self.header)
        self.content = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setMinimumSize(QtCore.QSize(0, 0))
        self.content.setAutoFillBackground(False)
        self.content.setStyleSheet("background-color:white;\n"
"")
        self.content.setTitle("")
        self.content.setObjectName("content")
        self.verticalLayout.addWidget(self.content)
        self.footer = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footer.sizePolicy().hasHeightForWidth())
        self.footer.setSizePolicy(sizePolicy)
        self.footer.setMinimumSize(QtCore.QSize(0, 0))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 51))
        self.footer.setStyleSheet("*{\n"
"background-color:white;\n"
"}")
        self.footer.setTitle("")
        self.footer.setObjectName("footer")
        self.verticalLayout.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HomeButton.setText(_translate("MainWindow", "HOME"))
        self.SearchButton.setText(_translate("MainWindow", "SEARCH"))
        self.SignOutButton.setText(_translate("MainWindow", "Sign Out"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
