# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 889)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("border-image: url(:/logo/Untitled.jpg);")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(390, 431))
        self.groupBox_2.setStyleSheet("border-image: url(:/logo/login.jpg);\n"
"border-radius: 20px;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.loginButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loginButton.setGeometry(QtCore.QRect(50, 320, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("border-image: none;\n"
"background-color: rgb(0, 151, 218);\n"
"border-style:solid;\n"
"border-width:1px;\n"
"color:white;\n"
"border-radius: 10px;\n"
"border-color: rgb(162, 162, 162)")
        self.loginButton.setObjectName("loginButton")
        self.passwordlogo = QtWidgets.QLabel(self.groupBox_2)
        self.passwordlogo.setGeometry(QtCore.QRect(70, 240, 21, 21))
        self.passwordlogo.setText("")
        self.passwordlogo.setPixmap(QtGui.QPixmap(":/logo/2A.jpg"))
        self.passwordlogo.setScaledContents(True)
        self.passwordlogo.setObjectName("passwordlogo")
        self.nimLine_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.nimLine_2.setGeometry(QtCore.QRect(100, 190, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.nimLine_2.setFont(font)
        self.nimLine_2.setStyleSheet("border-image : none;\n"
"margin-bottom: 5px")
        self.nimLine_2.setText("")
        self.nimLine_2.setCursorPosition(0)
        self.nimLine_2.setDragEnabled(False)
        self.nimLine_2.setReadOnly(False)
        self.nimLine_2.setClearButtonEnabled(False)
        self.nimLine_2.setObjectName("nimLine_2")
        self.profilelogo = QtWidgets.QLabel(self.groupBox_2)
        self.profilelogo.setGeometry(QtCore.QRect(70, 190, 21, 21))
        self.profilelogo.setText("")
        self.profilelogo.setPixmap(QtGui.QPixmap(":/logo/1A.jpg"))
        self.profilelogo.setScaledContents(True)
        self.profilelogo.setObjectName("profilelogo")
        self.passwordLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.passwordLine.setGeometry(QtCore.QRect(100, 240, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLine.setFont(font)
        self.passwordLine.setStyleSheet("border-image: none;\n"
"margin-bottom: 5px;")
        self.passwordLine.setText("")
        self.passwordLine.setCursorPosition(0)
        self.passwordLine.setDragEnabled(False)
        self.passwordLine.setReadOnly(False)
        self.passwordLine.setClearButtonEnabled(True)
        self.passwordLine.setObjectName("passwordLine")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(50, 180, 291, 41))
        self.label.setStyleSheet("border-image: none;\n"
"background-color: white;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"color:white;\n"
"border-radius: 10px;\n"
"border-color: rgb(162, 162, 162)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 230, 291, 41))
        self.label_2.setStyleSheet("border-image: none;\n"
"background-color: white;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"color:white;\n"
"border-radius: 10px;\n"
"border-color: rgb(162, 162, 162)")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.loginButton.raise_()
        self.passwordlogo.raise_()
        self.nimLine_2.raise_()
        self.profilelogo.raise_()
        self.passwordLine.raise_()
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginButton.setText(_translate("MainWindow", "LOGIN"))
        self.nimLine_2.setPlaceholderText(_translate("MainWindow", "NIM / Binusian ID"))
        self.passwordLine.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
