# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Any
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QDialog, QMessageBox
from PyQt5.QtWidgets import *
from mainpage import Ui_MainWindow

def openAccount():
    with open("C:/Users/Asus/OneDrive/Desktop/BIA/data/account.txt", "r") as file:
        lines = file.readlines()
    for line in lines:
        acc = line.strip().split("#")
    return Account(acc[0], acc[1], acc[2], acc[3], acc[4], acc[5], acc[6], acc[7], acc[8], acc[9], acc[10], acc[11], acc[12])

class Account():
    def __init__(self, name, nim, password, degree, age, loc, ipk, fav, skill, career, company, exp, mbti):
        self.name = name
        self.nim = nim
        self.password = password
        self.degree = degree
        self.age = age
        self.loc = loc
        self.ipk = ipk
        self.fav = fav
        self.skill = skill
        self.career = career
        self.company = company
        self.exp = exp
        self.mbti = mbti
        
    def get_name(self):
        return self.name
    def get_nim(self):
        return self.nim
    def get_password(self):
        return self.password
    def get_degree(self):
        return self.degree
    def get_age(self):
        return self.age
    def get_loc(self):
        return self.loc
    def get_ipk(self):
        return self.ipk
    def get_fav(self):
        return self.fav
    def get_skill(self):
        return self.skill
    def get_career(self):
        return self.career
    def get_company(self):
        return self.company
    def get_exp(self):
        return self.exp
    def get_mbti(self):
        return self.mbti

acc = openAccount()


class Ui_Login(object):
    
    def loginfunction(self):
        nim = self.nimLine.text()
        password = self.passwordLine.text()
        _translate = QtCore.QCoreApplication.translate
       
        if nim == acc.nim and password == acc.password:
            print("Login Successful")
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.showMaximized()
        else:
            self.nimLine.clear()
            self.passwordLine.clear()
            self.nimLine.setPlaceholderText(_translate("Login", "Incorrect NIM"))
            self.passwordLine.setPlaceholderText(_translate("Login", "Incorrect Password"))

            

    def setupUi(self, Login):
        
        Login.setObjectName("Login")
        Login.resize(1143, 767)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("border-image: url(:/logo/Untitled.jpg);")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(390, 431))
        self.groupBox_2.setStyleSheet("border-image: url(:/logo/login.jpg); border-radius: 20px;\n"
"\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.loginButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loginButton.setGeometry(QtCore.QRect(50, 320, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("border-image: none;\n"
"background-color: rgb(0, 151, 218);\n"
"border-style:solid;\n"
"border-width:1px;\n"
"color:white;\n"
"border-radius: 10px;\n"
"border-color: rgb(162, 162, 162)")
        self.loginButton.setObjectName("loginButton")
        self.loginButton.clicked.connect(self.loginfunction)
        # self.loginButton.clicked.connect(Login.close)
        self.passwordlogo = QtWidgets.QLabel(self.groupBox_2)
        self.passwordlogo.setGeometry(QtCore.QRect(70, 240, 21, 21))
        self.passwordlogo.setText("")
        self.passwordlogo.setPixmap(QtGui.QPixmap(":/logo/assets/2A.jpg"))
        self.passwordlogo.setScaledContents(True)
        self.passwordlogo.setObjectName("passwordlogo")
        self.nimLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.nimLine.setGeometry(QtCore.QRect(100, 190, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.nimLine.setFont(font)
        self.nimLine.setStyleSheet("border-image : none;\n"
"margin-bottom: 5px")
        self.nimLine.setText("")
        self.nimLine.setCursorPosition(0)
        self.nimLine.setDragEnabled(False)
        self.nimLine.setReadOnly(False)
        self.nimLine.setClearButtonEnabled(False)
        self.nimLine.setObjectName("nimLine")
        self.profilelogo = QtWidgets.QLabel(self.groupBox_2)
        self.profilelogo.setGeometry(QtCore.QRect(70, 190, 21, 21))
        self.profilelogo.setText("")
        self.profilelogo.setPixmap(QtGui.QPixmap(":/logo/assets/1A.jpg"))
        self.profilelogo.setScaledContents(True)
        self.profilelogo.setObjectName("profilelogo")
        self.passwordLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.passwordLine.setGeometry(QtCore.QRect(100, 240, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLine.setFont(font)
        self.passwordLine.setStyleSheet("border-image: none;\n"
"margin-bottom: 5px;\n"
"lineedit-password-character: 42;")
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLine.setText("")
        self.passwordLine.setCursorPosition(0)
        self.passwordLine.setDragEnabled(False)
        self.passwordLine.setReadOnly(False)
        self.passwordLine.setClearButtonEnabled(True)
        self.passwordLine.setObjectName("passwordLine")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(50, 180, 291, 41))
        self.label.setStyleSheet("border-image: none;\n"
"background-color: white;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"color:white;\n"
"border-radius: 10px;\n"
"border-color: rgb(162, 162, 162)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 230, 291, 41))
        self.label_2.setStyleSheet("border-image: none;\n"
"background-color: white;\n"
"border-style:solid;\n"
"border-width:1px;\n"
"color:white;\n"
"border-radius: 10px;\n"
"border-color: rgb(162, 162, 162)\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.loginButton.raise_()
        self.passwordlogo.raise_()
        self.nimLine.raise_()
        self.profilelogo.raise_()
        self.passwordLine.raise_()
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addWidget(self.groupBox)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.loginButton.setText(_translate("Login", "LOGIN"))
        self.nimLine.setPlaceholderText(_translate("Login", "NIM / Binusian ID"))
        self.passwordLine.setPlaceholderText(_translate("Login", "Password"))
        self.label.setText(_translate("Login", "TextLabel"))
        self.label_2.setText(_translate("Login", "TextLabel"))
import test_rc




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.showMaximized()
    sys.exit(app.exec_())
